# Generated by Django 5.0.1 on 2024-02-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=255, null=True)),
                ('Street', models.CharField(max_length=255, null=True)),
                ('Town', models.CharField(max_length=255, null=True)),
                ('City', models.CharField(max_length=255, null=True)),
                ('PostalCode', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerId', models.IntegerField()),
                ('ProductId', models.CharField(default=0, max_length=255, null=True)),
                ('OrderDate', models.CharField(max_length=255)),
                ('Status', models.IntegerField()),
                ('Qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Price', models.IntegerField()),
                ('DateAdded', models.CharField(max_length=255)),
                ('Distributor', models.CharField(max_length=255)),
            ],
        ),
    ]
